Haskell Day 2019向けのCode Of Conductを作成
haskell-jp/community pull request #24
Opened 2019-10-27 09:47 UTC by igrep

https://github.com/haskell-jp/community/issues/23
突貫工事になってしまいましたが、何人かに見ていただいた上で、マージし、イベントページにリンクを張り次第クローズします。

2019-10-27 10:22 UTC, matsubara0507 approved these changes

2019-10-28 05:41 UTC, yotsuya approved these changes

2019-10-28 11:33 UTC, kakkun61 requested changes
全体的にこまかいところですが

2019-10-28 11:33 UTC, kakkun61 commented on haskell-day-2019/CODE_OF_CONDUCT.md
> +そのためには、性別や人種など多様な背景を持つ、普段の生活では会わない人々同士でも、互いに敬意を払って楽しい時間を過ごせることが重要だと考えています。
本筋ではないこまいところなんですが、空行なしの改行だと空白の入った1行になるので、空白が気になります。

2019-10-28 11:33 UTC, kakkun61 commented on haskell-day-2019/CODE_OF_CONDUCT.md
> +-   他の参加者に対するナンパ行為(容姿に関する発言、恋愛・性的興味を目的とした発言)や不適切な身体的接触を行うこと
全角括弧と半角括弧の表記揺れ。個人的には和文だと全角括弧の方が好き。

2019-10-28 11:33 UTC, kakkun61 commented on haskell-day-2019/CODE_OF_CONDUCT.md
> +### ライセンスと帰属に関して
「報告窓口」の子要素じゃないように思えるので、第2レベルがいいと思います。

2019-10-28 11:33 UTC, kakkun61 commented on haskell-day-2019/CODE_OF_CONDUCT.md
> +自分や他の人がハラスメントを受けた場合には(TODO: スタッフの確認方法)に直接ご連絡いただくか、[haskell-jp-admins@googlegroups.com](mailto:haskell-jp-admins@googlegroups.com)までご連絡ください。
メールアドレスの後に空白がない（他の欧文和文の間にはある）。

2019-10-28 23:39 UTC, maoe commented
LGTM. Thank you!

2019-10-29 08:37 UTC, kakkun61 requested changes
またまたこまいですが…… :bow:

suggestion にしてるのでポチポチとお願いします :bow:

2019-10-29 08:37 UTC, kakkun61 commented on haskell-day-2019/CODE_OF_CONDUCT.md
> +自分や他の人がハラスメントを受けた場合には(TODO: スタッフの確認方法)に直接ご連絡いただくか、 [haskell-jp-admins@googlegroups.com](mailto:haskell-jp-admins@googlegroups.com) までご連絡ください。
句読点自体にアキがあるので句読点と欧文の間はスペースなしにしたいです。

統一されていればいいのですが、「採用されており、Haskell Day 2019 もその精神に」やその他はスペースがないので……

```suggestion
自分や他の人がハラスメントを受けた場合には(TODO: スタッフの確認方法)に直接ご連絡いただくか、[haskell-jp-admins@googlegroups.com](mailto:haskell-jp-admins@googlegroups.com) までご連絡ください。
```

2019-10-29 08:37 UTC, kakkun61 commented on haskell-day-2019/CODE_OF_CONDUCT.md
> +本規範は [ScalaMatsuri](http://scalamatsuri.org/) の規範を元に、 Haskell Day 2019 固有の事情に合わせて改変しました。ScalaMatsuri の規範は Geek Feminism wiki の規範例から派生しており、PNW Scala、NE Scala、および Scala Days の影響を受けています。
```suggestion
本規範は [ScalaMatsuri](http://scalamatsuri.org/) の規範を元に、Haskell Day 2019 固有の事情に合わせて改変しました。ScalaMatsuri の規範は Geek Feminism wiki の規範例から派生しており、PNW Scala、NE Scala、および Scala Days の影響を受けています。
```

2019-10-30 02:26 UTC, kakkun61 approved these changes

2019-10-30 04:51 UTC, merged

2019-10-30 04:52 UTC, igrep commented
皆さんレビューありがとうございました！
![IMG_20180408_093101](https://user-images.githubusercontent.com/227057/67830020-8c1ede00-fb1c-11e9-8753-661ea0bfdb9b.jpg)